### ISSUE TITLE
Instructions to run the project please!

### ISSUE THREAD

**Issue by sganesh1975** [pragatisawarkar/Sadhguru_Amrittulya#1]
@pragatisawarkar Please provide clear step by step instructions on how to run this project.

**Comment by pragatisawarkar** [comment]
1) Please select the location where to clone the repository and type cmd

2) git clone https://github.com/pragatisawarkar/Sadhguru_Amrittulya.git

3) create new virtual environment 

4)open pycharm and open project from clone repository and add virtual environment and activate it

5) install (https://pypi.org/project/sorl-thumbnail/) by using (pip install sorl-thumbnail) with version sorl-thumbnail==12.6.3 for create a image thumbnail

6)create database amrit_tulya and apply makemigrations (py manage.py makemigrations) on it and migrate(py manage.py migrate) it.

7)Run the server by using py manage.py runserver

**Comment by pragatisawarkar** [comment]
Please refer this ..If possible try to provide me remote access of your PC if it will not work.
